### ISSUE TITLE
 Cannot use traditional chinese characters 

### ISSUE THREAD

**Issue by AruXc** [moreta/vue-search-select#100]
In input write traditional chinese characters  cannot invoked search feature
How can I resolve this problem?

**Comment by moreta** [comment]
Chinese characters need completion action by enter key?
v-model do not bind while typing.

vue-search-select not support yet.
If you have your v-model, you can bind like this 
https://gist.github.com/moreta/b48fc8ac946932826be9a8d1fd673634
Japanese input also have same issue.

**Comment by AruXc** [comment]
Yes. When I typing Chinese characters  also need enter to complete.

vue-search-select  not support  typing Chinese or Japanese because v-model do not bind?

OK, by the way can I load in page focus on input?

**Comment by moreta** [comment]
I know solution for IME (Chinese, Japanese), but thank you links.

I will add feature later. or welcome PR.

**Comment by moreta** [comment]
ModelSelect Component(or Others) input tag has ref=input.
So, you can reference it by $refs from Parent component.

ex)
```
<model-select :options="options"
                      v-model="item"
                      placeholder="placeholder text"
                      ref="mselect">
        </model-select>

...
  mounted () {
    this.$nextTick(() => {
      console.log(this.$refs.mselect.$refs.input)
      const el = this.$refs.mselect.$refs.input
      el.focus()
    })
  },
```

**Comment by moreta** [comment]
Please use v2.7.1.
It should work.

**Comment by AruXc** [comment]
OK, thank you, I just being done PR LOL 
focus I will try tomorrow. Thanks a lot, have a good day
