### ISSUE TITLE
CSS not applied with version 2.9.1

### ISSUE THREAD

**Issue by js-pace** [moreta/vue-search-select#124]
I was running version 2.8.3 and it was working fine but after upgrading to version 2.9.1 the dropdown's CSS has gone, it displays only an input field and in the suggestion list, there is no CSS at all, suggestion list is also a plain text. I am attaching the screenshot for reference.
<img width="434" alt="Screenshot 2019-08-29 at 4 16 44 PM" src="https://user-images.githubusercontent.com/49482856/63936093-70de1680-ca78-11e9-8ad2-d426f530502f.png">

**Comment by moreta** [comment]
Are you import css?

After 2.9.1 css extracted standalone file.

```
import 'vue-search-select/dist/VueSearchSelect.css'
```

**Comment by js-pace** [comment]
@moreta thank tou very much, I didn't check the docs, imported this CSS and it worked.
