### ISSUE TITLE
Error for last update vue-search-select

### ISSUE THREAD

**Issue by kusumalubis** [moreta/vue-search-select#125]
I found error display after I update to the last version.

before my select-search input displayed like this:
![image](https://user-images.githubusercontent.com/8085993/64105384-553c7e00-cda0-11e9-8d1b-9d07e0bfeb23.png)
but after I update to the last version to be like this
![image](https://user-images.githubusercontent.com/8085993/64105304-2c1bed80-cda0-11e9-9c51-f31aafd1580b.png)

Any explanation? 
Thank you before

**Comment by Dhu-kmw** [comment]
Run into the same issue.
Looks like you need to
`import 'vue-search-select/dist/VueSearchSelect.css';`
after updating to 2.9.1

**Comment by moreta** [comment]
#124
