### ISSUE TITLE
Possible to make a value required?

### ISSUE THREAD

**Issue by euoia** [moreta/vue-search-select#127]
Other HTML form elements allow you to specify that a value is required with the _required_ attribute.

Is it possible to add something similar to these components?

**Comment by moreta** [comment]
ModelSelect has isError prop.
But this prop just change color to red.

If you need to value is required,
you can use [vuelidate](https://github.com/vuelidate/vuelidate) or [simple-vue-validator](simple-vue-validator).
These validation library work with v-model value.
Or you can also write custom validation logic.
