### ISSUE TITLE
Unable to use pnpm to install the module

### ISSUE THREAD

**Issue by DeeGeeMan** [moreta/vue-search-select#131]

**Comment by DeeGeeMan** [comment]
I tried to use **pnpm** to install **vue-search-select**, but it failed to include all the necessary components.

Here is the current folder structure after installing it into **node_modules** folder:
├── README.md
├── dist
│   ├── VueSearchSelect.common.js
│   ├── VueSearchSelect.common.js.map
│   ├── VueSearchSelect.css
│   ├── VueSearchSelect.umd.js.map
│   ├── VueSearchSelect.umd.min.js.map
│   └── demo.html
├── package.json
└── src
    ├── assets
    │   └── lib
    │       ├── button.css
    │       ├── dropdown.css
    │       ├── label.css
    │       ├── lib.scss
    │       └── override.scss
    └── lib
        ├── BasicSelect.vue
        ├── ListSelect.vue
        ├── ModelListSelect.vue
        ├── ModelSelect.vue
        ├── MultiListSelect.vue
        ├── MultiSelect.vue
        ├── common.js
        ├── index.js
        └── utils.js

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v2.9.2

Sorry, npmignore was the problem.
