### ISSUE TITLE
how to get change value

### ISSUE THREAD

**Issue by kmihiranga** [moreta/vue-search-select#139]
i want to get every time @change value into a console. how i get?

**Comment by BetoHu** [comment]
I have this 
`<template>
    <model-select
            :options="options"
            v-model="changeEvent"
            placeholder="select item">
    </model-select>
</template>`

`<script>
    import {ModelSelect} from 'vue-search-select'

    export default {
        components: {
            ModelSelect
        },
        data() {
            return {
                value: '',
                changeEvent: this.value,
                options: []
            }
        },
        watch: {
            changeEvent(val) {
                // eslint-disable-next-line no-console
                console.log(val);
            }
        }
    }
</script>`

**Comment by meSmashsta** [comment]
Use @input="myChange"
