### ISSUE TITLE
demo not working ( _h is not defined)

### ISSUE THREAD

**Issue by paOol** [moreta/vue-search-select#16]
copy / pasted from the example.
on vue v2.1.6

here is the console output (shortened)
```
[Vue warn]: Error when rendering component <basic-select>: 
```
```
vue.runtime.common.js?d43f:2961 Uncaught ReferenceError: _h is not defined

backend.js:1 [vue-devtools] Ready. Detected Vue v2.1.6
```

using this if it matters
https://github.com/egoist/vuepack

**Comment by moreta** [comment]
Thank you report.
Yes I have same problem. Maybe cause is vue version.
I'll fix it.

**Comment by moreta** [comment]
FIXED https://github.com/moreta/vue-search-select/releases/tag/v2.3.3
