### ISSUE TITLE
Typescript Support?

### ISSUE THREAD

**Issue by LizAinslie** [moreta/vue-search-select#162]
I noticed there are no type definitions either in this project or from DefinitelyTyped, essentially making this project useless to people trying to use it in Vue + TypeScript projects.

It also hasn't seen updates since September of 2021, so I also wondered if someone has made a more recent fork with possible TypeScript support, as I have not the time (or desire) to write type definitions of my own.

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v3.0.4

**Comment by LizAinslie** [comment]
Awesome 😎
