### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by amchconsult** [moreta/vue-search-select#163]
Hi 
Are you planning to do vue 3 version?
thank you

**Comment by rick20** [comment]
Hi @amchconsult, have you found the workaround for vue 3? Or did you find any similar package?
Thank you.

**Comment by Kakulukian** [comment]
Hey,
I wanted the ModelSelect component in vue 3, it's not working due to breaking changes but here ModelSelect's reimplementation if you need to:
https://gist.github.com/Kakulukian/4b2a349d74e01bef034d81cb5968f8a5

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v3.0.4
