### ISSUE TITLE
"is-disabled" prop is not working properly for "MultiSelect" and "MultiListSelect"

### ISSUE THREAD

**Issue by amal-qb** [moreta/vue-search-select#178]
"is-disabled" prop allows selection if the user clicks the input's label for "MultiSelect" and "MultiListSelect" components.

### Steps to reproduce:
1. Click the label associated with the "MultiSelect".
2. Press the down arrow key on the keyboard to select an item.
3. Press the "Enter" key.

The bug is reproducible on https://vue-search-select.netlify.app/#/multi and https://vue-search-select.netlify.app/#/multi-list .

**Comment by moreta** [comment]
Thank you
