### ISSUE TITLE
Case Insensitive Search?

### ISSUE THREAD

**Issue by Eder87rh** [moreta/vue-search-select#18]
Is there a way to search with Case Insensitive option?

**Comment by moreta** [comment]
Since  v2.3.2 search with case insensitive(Default).

There is no option yet.

**Comment by moreta** [comment]
Sorry wrong answer.

BasicSelect component search with Case Insensitive.
But MultiSelect don't I'll fix this. :sweat:

**Comment by moreta** [comment]
fixed at v2.3.4

https://github.com/moreta/vue-search-select/releases/tag/v2.3.4
