### ISSUE TITLE
How to add placeholder?

### ISSUE THREAD

**Issue by pavinthan** [moreta/vue-search-select#21]
how to add placeholder for multi select or basic select dropdown?

**Comment by moreta** [comment]
I add placehoolder prop at v2.3.6

https://github.com/moreta/vue-search-select/releases/tag/v2.3.6

**Comment by pavinthan** [comment]
Thanks @moreta

**Comment by whfamily2006** [comment]
version: 2.4.0
Why placeholder props not working?
```
<model-select :options = "sessions" v-model = "searchForm.sessionId"
			title = "Select session" style = "width: 100%; display: inline-block"
			placeholder="select item">
</model-select >
```
Browser image where select model used: 
![image](https://user-images.githubusercontent.com/9881496/33013816-1d814134-ce07-11e7-9818-2626d1dd4c37.png)
