### ISSUE TITLE
Supply value as a string rather than an object

### ISSUE THREAD

**Issue by alexcroox** [moreta/vue-search-select#22]
I'd like to be able to use `:selected-option="value"` where `value` is just the value for the select, rather than an object with the text + value. 

Currently I have to store both the text and value in a cookie in order to correctly pre-fill the select on next page load. This is frustrating when `text` for that value could change over time and would therefore fall out of sync with my cookie.

**Comment by moreta** [comment]
Use ModelSelect component.
Added at v2.3.8
