### ISSUE TITLE
Consider using modular lodash

### ISSUE THREAD

**Issue by alexcroox** [moreta/vue-search-select#23]
I'm trying to reduce my overall bundle size and noticed this lib uses the full lodash library, consider reducing the dependency size by using the [modular parts of lodash](https://www.npmjs.com/package/lodash.foreach) you need rather than the entire library if possible :)

![ss](https://cl.ly/jaKD/Screen%20Shot%202017-03-16%20at%2010.57.23.png)

**Comment by moreta** [comment]
Thank you for your advice.
I'll fix this!

**Comment by rmmcnulty9** [comment]
Doing it this way will probably be easier than having different npm packages: https://gist.githubusercontent.com/rcdexta/77e2198e4b552b027e12480e3c7a1922/raw/f20af6d3642c340b4d7268264d1eddf549a3d993/js_lib_import.js

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v2.5.0
