### ISSUE TITLE
Why does not work with gulp?

### ISSUE THREAD

**Issue by trocho** [moreta/vue-search-select#41]
Hi @moreta 

I have a problem when I'm loading your package.
I'm using gulp, browserify and babelify.

Any idea?

`Error: Cannot find module '!!./../../../node_modules/css-loader/index.js!./../../../node_modules/vue-loader/lib/style-rewriter.js?id=data-v-3bdee3a6!./../../../node_modules/vue-loader/lib/selector.js?type=styles&index=1!./ModelSelect.vue' from '/var/www/withpassion/docker-projects/wesele123.local/html/node_modules/vue-search-select/publish'`

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v2.9.1
