### ISSUE TITLE
Automatically change the width when selecting an option

### ISSUE THREAD

**Issue by superrandres** [moreta/vue-search-select#49]
When selecting an option, the width of the select is automatically stretched making my modal in view for telephones disengage a little. This does not happen with any other component and also the options that I select are very short texts.

![image](https://user-images.githubusercontent.com/8306417/33131527-ce11db86-cf64-11e7-9b45-f0a5aa048e19.png)

As you can see there has already stretched the width of the entire modal because of the select

**Comment by moreta** [comment]
From v2.9.1

Input width is 100%(when using without semantic-ui) 
or Follow semantic-ui's spec.

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v2.9.1
