### ISSUE TITLE
Placeholder props not working

### ISSUE THREAD

**Issue by whfamily2006** [moreta/vue-search-select#50]
version: 2.4.0
Why placeholder props not working?
```
<model-select :options = "sessions" v-model = "searchForm.sessionId"
			title = "Select session" style = "width: 100%; display: inline-block"
			placeholder="select item">
</model-select >
```
Browser image where select model used:

![image](https://user-images.githubusercontent.com/9881496/33176583-5ac3f966-d081-11e7-8f1f-d3830b6462b0.png)

**Comment by whdckszxxx** [comment]
same here

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v2.5.0
