### ISSUE TITLE
Selecting an option programmatically has a bug.

### ISSUE THREAD

**Issue by xcodder** [moreta/vue-search-select#66]
I have a select component.
I opened it and clicked on the third option - "Need Confirmation"
I then at some time reseted to the first option with the following code:
`this.item = this.options[0]
`
It seemed to work OK until I pressed on the select  again and the third option is highlighted instead of the first one.

![opera snapshot_2018-03-29_164327_localhost](https://user-images.githubusercontent.com/29988811/38092246-66062a2c-3370-11e8-938f-c94b77e14c8a.png)

You can see as well that the text in the text box shows that it is indeed fixated on the first option but still highlighting the third.

**Comment by moreta** [comment]
fixed v2.6.3
