### ISSUE TITLE
Error with Nuxt: "Cannot read property 'middleware' of undefined"

### ISSUE THREAD

**Issue by paulrosen** [moreta/vue-search-select#67]
When putting this in a Nuxt-based project, I get "Cannot read property 'middleware' of undefined", which usually means that the component is doing something on the server side that it can't do.

Does anyone know of a workaround for this?

To recreate, create a project like this:
```
npx create-nuxt-app my-project
```
And add the component exactly as the example shows. When loading the page, the above message appears.

**Comment by paulrosen** [comment]
It really was a generic project. That was a while ago, so I don't remember other than my steps to reproduce above. Here's my current set of dependencies, if that helps:
```
  "dependencies": {},
  "devDependencies": {
    "@fortawesome/fontawesome": "^1.1.4",
    "@fortawesome/fontawesome-free-solid": "^5.0.8",
    "@fortawesome/vue-fontawesome": "0.0.22",
    "@nuxtjs/axios": "^5.3.1",
    "@nuxtjs/pwa": "^2.0.8",
    "abcjs": "^4.0.1",
    "babel-eslint": "^8.2.2",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "cross-env": "^5.1.4",
    "eslint": "^4.18.2",
    "eslint-config-standard": "^11.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.2",
    "nuxt": "^1.3.0",
    "vue-select": "^2.4.0",
    "vue2-touch-events": "^1.0.0",
    "whatwg-fetch": "^2.0.4"
  }
```
Note that I'm using a different select library at the moment, but I'd like to evaluate yours, so if I can get it running I'll try them side by side.

**Comment by moreta** [comment]
Thank you. I'll try it

I think [vue-multiselect](https://vue-multiselect.js.org/) is the vuejs's best select library. :joy:
