### ISSUE TITLE
Allow css customizations on custom properties (Feature Request)

### ISSUE THREAD

**Issue by javiercbk** [moreta/vue-search-select#69]
An item should have a `text` and a `value`, but it could have other custom properties without interfering with the library's normal behavior.

I want to allow css customizations on some custom property in order to change the color (or any) css property.

I've created a [PR](https://github.com/moreta/vue-search-select/pull/70) that addresses this feature.

**Comment by moreta** [comment]
Thank you for your PR.

I'm release [this v2.6.0](https://github.com/moreta/vue-search-select/tree/v2.6.0)

**Comment by javiercbk** [comment]
Thanks, I've updated the examples page as well, so you might want to update your `gh-page` branch as well
