### ISSUE TITLE
Multi select delete icon  not showig

### ISSUE THREAD

**Issue by chanduzalte** [moreta/vue-search-select#73]
Everything works great

But delete > icon:before is not rendered in DOM 

<i data-v-a3dbfc0c="" class="delete icon"></i>
inspect element doesnt shows :before and its css

I have tried to apply :before css to it  but no luck

**Other icons are shown properly like - <i data-v-a3dbfc0c="" class="dropdown icon"></i>

**Comment by bovesan** [comment]
I was struggling with this as well. Turns out it requires the Semantic-Org CSS mentioned in the top of the [README](https://github.com/moreta/vue-search-select/blob/master/README.md)

Workaround css:
```
.multiple.search .delete.icon:before {
	font-family: sans-serif;
	content: "x";
	font-style: normal; 
}
```

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v2.9.1
