### ISSUE TITLE
How to autofocus?

### ISSUE THREAD

**Issue by euoia** [moreta/vue-search-select#74]
Hi,

Can you advise on how I can autofocus the input on page load?

Thanks,

James

**Comment by euoia** [comment]
I figured it out. By giving the <model-select> a ref like `<model-select ref="payeeSelect">`, I can use the following in the component's `mounted` function:

```
    this.$refs.payeeSelect.$refs.input.focus();
```

**Comment by coycash** [comment]
This isn't working for me, would you mind posting some more of your code?  Thanks

**Comment by moreta** [comment]
May be this works.

```
<model-select :options="options"
                      v-model="item"
                      placeholder="placeholder text"
                      ref="mselect">
        </model-select>

...
  mounted () {
    this.$nextTick(() => {
      console.log(this.$refs.mselect.$refs.input)
      const el = this.$refs.mselect.$refs.input
      el.focus()
    })
  },
```
