### ISSUE TITLE
How to fire an event when option selected?

### ISSUE THREAD

**Issue by BrunoVGG** [moreta/vue-search-select#75]
Hi,

how to call an method when selected a option?
Please, a exemple... =)

Thanks!

**Comment by riksnelders** [comment]
Same problem here. @select doesnt work.
@moreta  Update docs if this is fixed please..

**Comment by bovesan** [comment]
It seems @select works with basic-select, but not model-select.

**Comment by redenfm** [comment]
same issue here. any other workaround?

**Comment by moreta** [comment]
OK.
ModelSelect component use v-model.
And v-model just alias "v-bind:value" and "v-on:input". [see this vue official docs](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components)

So this code
```js
<model-select :options="options" v-model="item"></model-select>
```

is same as

```js
<model-select :options="options" :value="item" @input="handleOnInput"></model-select>
```

If you want handle on select event on v-model you should use on input event.(not select event)

I added sample code .
<https://github.com/moreta/vue-search-select/commit/daa5c5e037365099ecba528e21fbc17d051c34c7>
