### ISSUE TITLE
UI sizie

### ISSUE THREAD

**Issue by Jochii12** [moreta/vue-search-select#81]
hello can i ask if can rezise select to this small ? like this ?

![image](https://user-images.githubusercontent.com/35551627/42355716-13afa846-8101-11e8-850b-021334c51f3a.png)

Thank you sir

**Comment by moreta** [comment]
From v2.9.1
Follow semantic-ui's spec.

Or if you use without semantic-ui version.
you can change size by change font-size
semantic-ui's size "em"  based. so you change font-size ui size also change.

see override.scss
https://github.com/moreta/vue-search-select/blob/v2.9.1/src/assets/lib/override.scss#L3

```
.ui.dropdown {
  box-sizing: border-box; /* for padding */
  font-size: 14px; /* for em size */
```

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v2.9.1
