### ISSUE TITLE
dynamically add input as well as dropdown in vue-search-select

### ISSUE THREAD

**Issue by rockyshukla** [moreta/vue-search-select#83]
I m trying to add a dynamical input along with dropdown for that i m using vue-serach-select let me show my code then issue in detail

            <template>
              <button @click="addRow1"></button>
              <table class="table table-striped">
                 <thead>
                   <tr style="font-size: 12px; text-align: center;">
                     <th class="span2" >Product Name</th>
                     <th class="span2" >Unit</th>
                   </tr>
         </thead> 
          <tbody id="product_table_body">
             <tr v-for="(row, index) in rows">
                  <td><model-list-select :list="productname"
                             option-value="product_name"
                             option-text="product_name"
                             v-model="row.selectproduct"
                             placeholder="Search Product Name"
                             @searchchange="searchprd3">
                     </model-list-select>        
                  </td>
                  <td>
                      <input class="form-control-sm" type="text" v-model="row.new1" disabled="disabled" style="width: 100px;">
                  </td>
             </tr>
           </tbody>
         </table>

      </template>
      <script>
      export default {
        data () {
           return {     
              productname3:[],
              rows:[],  
           }
       },
      methods:{
                  addRow1(){
                    this.rows.push({})
                  },
                
                  searchprd3(search,index){
                },
             }
         }
      </script>
now  if i click on button one more row is added with dropdown now my problem is that how i can differentiate productname according to dynamic create row i had tried like  :list="productname{index},:list="productname.index but none of them worked and last thing i want to pass index parameter in searchprd3 function so i tried like this searchprd3(search,index) in function I m getting index but it throw error for search and if only pass index then also throw error however it work none of parameter is passed from select like this @searchchange="searchprd3" but in function i m not getting index value

**Comment by moreta** [comment]
`@searchchange` emit just input text. (not index)
`@searchchange` do not emit selected option value
Selected option value set directly v-model. In this case row.selectproduct.

`productname` is Array? And `productname.index` also Array?(Array in Array?)
Then you can create method or computed(with parameter).

```
<tr v-for="(row, index) in rows">
    <model-list-select :list="productnameAtIndex(index)" 
```
```
methods: {
    productnameAtIndex(index) {
        this.productname[index]
    }
}
```
