### ISSUE TITLE
How to increase font size

### ISSUE THREAD

**Issue by davidhernandeze** [moreta/vue-search-select#84]
Hi i want to know how i can increase de font size of the options

**Comment by peterlupu** [comment]
hi, maybe this will help someone; maybe there's a better way but I didn't want to spend more than a few minutes on this issue.

I just added this to my app's css:

.ui.dropdown .menu > .item {
  font-size: 1em !important;
}

**Comment by moreta** [comment]
From v2.9.1
Follow semantic-ui's spec.

Or if you use without semantic-ui version.
you can change size by change font-size
semantic-ui's size "em"  based. so you change font-size ui size also change.

see override.scss
https://github.com/moreta/vue-search-select/blob/v2.9.1/src/assets/lib/override.scss#L3

```
.ui.dropdown {
  box-sizing: border-box; /* for padding */
  font-size: 14px; /* for em size */
```

**Comment by moreta** [comment]
https://github.com/moreta/vue-search-select/releases/tag/v2.9.1
