### ISSUE TITLE
ID for search input

### ISSUE THREAD

**Issue by dermansi** [moreta/vue-search-select#85]
Hey,

great work with this component, we enjoy using it.

We are currently optimizing for Google Lighthouse and noticed that we can't set an ID for the search input and thus can't link a label. Do you mind adding a prop?

Thanks
dermansi

**Comment by moreta** [comment]
id prop added at v2.8.0

**Comment by moreta** [comment]
Sorry.
Props added to other components.

https://github.com/moreta/vue-search-select/releases/tag/v2.8.2
