### ISSUE TITLE
Multi-select option-value not working?

### ISSUE THREAD

**Issue by Tropicalista** [moreta/vue-search-select#93]
I'm trying this code: 

```
        <multi-select :options="options"
                      option-value="label"
                      option-text="group"
                      :selected-options="items"
                      placeholder="select item"
                      @select="onSelect">

```

My data is:

```
        options: [
          { label: '1', group: 'aa' },
          { label: '2', group: 'ab' }
        ],

```

**Comment by moreta** [comment]
**MultiListSelect** have optionValue, optionText prop. Not MultiSelect

**Comment by igasparetto** [comment]
> **MultiListSelect** have optionValue, optionText prop. Not MultiSelect

@moreta Not sure I understood your answer.
I have the same problem here.

What is wrong with his code?

**Comment by moreta** [comment]
MultiSelect and MultiListSelect are different component.
MultiListSelect is a component wrapping MultiSelect.
https://github.com/moreta/vue-search-select/blob/master/src/components/lib/MultiListSelect.vue

MultiSelect component does not have optionValue and optionText prop.
MultiListSelect component have  optionValue and optionText prop.

```
<multi-list-select : list="options"
                      option-value="label"
                      option-text="group"
                      : selected-items="items"
                      placeholder="select item"
                      @select="onSelect">
```
https://github.com/moreta/vue-search-select/blob/master/src/components/sample/MultiList/_Basic.vue

**Comment by igasparetto** [comment]
I came here to answer my own question and you have already done that. Thank you!

I understood by looking at the Props: https://github.com/moreta/vue-search-select#props

Thanks again
