### ISSUE TITLE
The filter text doesn't disappear on the search input when type on mobile

### ISSUE THREAD

**Issue by dmpotapenko** [moreta/vue-search-select#97]
I tried to use plugin on mobile.
When I open a site in android's chrome browser a take this issue.

Fix:
replace
`v-model="searchText"`
with
`:value="searchText"
 @input="searchText = $event.target.value"`

In BasicSelect.vue on 
`<input
      class="search"
      autocomplete="off"
      tabindex="0"
      :value="searchText"
      @input="searchText = $event.target.value"
      ref="input"
      @focus.prevent="openOptions"
      @keyup.esc="closeOptions"
      @blur="blurInput"
      @keydown.up="prevItem"
      @keydown.down="nextItem"
      @keydown.enter.prevent
      @keyup.enter.prevent="enterItem"
      @keydown.delete="deleteTextOrItem"
    >` element

**Comment by moreta** [comment]
Released  at v2.7.1.

**Comment by dmpotapenko** [comment]
thank you so much!
